services:

  mongo:
    image: mongo
    restart: always
    logging:
      driver: none
    healthcheck:
      test:  echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  backend-test:
    build:
      context: backend
      dockerfile: ../Dockerfile.backend
    environment:
      DB_ADDRESS: mongodb://mongo:27017/mestodb
    command: npm run lint
    restart: 'no'
    depends_on:
      mongo:
        condition: service_healthy

  backend:
    build:
      context: backend
      dockerfile: ../Dockerfile.backend
    environment:
      DB_ADDRESS: mongodb://mongo:27017/mestodb
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 3001:3000
    healthcheck:
      interval: 10s
      timeout: 2s 
      start_period: 15s 
      retries: 5 
      test: node healthcheck.js

  frontend-test:
    build:
      context: frontend
      dockerfile: ../Dockerfile.frontend
    command: yarn test:microfrontend
    restart: 'no'
    environment:
          CI: true

  microfrontend-auth:
    container_name: auth
    build:
      context: frontend/microfrontend/auth
      dockerfile: ../../../Dockerfile.frontend
    ports:
      - 8097:8097
    expose:
      - "8097"
    volumes:
      - ./frontend/microfrontend/shared:/app/shared:ro
    depends_on:
      backend:
        condition: service_healthy
    network_mode: "host"

  microfrontend-cardboard:
    container_name: cardboard
    build:
      context: frontend/microfrontend/cardboard
      dockerfile: ../../../Dockerfile.frontend
    ports:
      - 8096:8096
    expose:
      - "8096"
    volumes:
      - ./frontend/microfrontend/shared:/app/shared:ro
    depends_on:
      backend:
        condition: service_healthy
    network_mode: "host"

  microfrontend-profile:
    container_name: profile
    build:
      context: frontend/microfrontend/profile
      dockerfile: ../../../Dockerfile.frontend
    ports:
      - 8098:8098
    expose:
      - "8098"
    volumes:
      - ./frontend/microfrontend/shared:/app/shared:ro
    depends_on:
      backend:
        condition: service_healthy
    network_mode: "host"

  microfrontend-upload:
    container_name: upload
    build:
      context: frontend/microfrontend/upload
      dockerfile: ../../../Dockerfile.frontend
    ports:
      - 8099:8099
    expose:
      - "8099"
    volumes:
      - ./frontend/microfrontend/shared:/app/shared:ro
    depends_on:
      backend:
        condition: service_healthy
    network_mode: "host"

  microfrontend-host:
    container_name: host
    build:
      context: frontend/microfrontend/host
      dockerfile: ../../../Dockerfile.frontend
    ports:
      - 8095:8095
    expose:
      - "8095"
    volumes:
      - ./frontend/microfrontend/shared:/app/shared:ro
    depends_on:
      backend:
        condition: service_healthy
    network_mode: "host"
